{"name": "测试正确账号、错误密码情况下的登录", "status": "passed", "description": "登录失败：测试正确账号、错误密码登录", "attachments": [{"name": "log", "source": "4acd0070-fa4c-44fb-8fd7-94dbd710a88b-attachment.txt", "type": "text/plain"}], "start": 1749803162520, "stop": 1749803171088, "uuid": "31a4729c-54d8-497e-84ee-fc999664a890", "historyId": "9bafb470a3f5b2bc06ae6138b0479d4f", "testCaseId": "9bafb470a3f5b2bc06ae6138b0479d4f", "fullName": "test_dir.Login.test_001_loginfail.TestLoginFail#test_login_fail_case", "labels": [{"name": "suite", "value": "登录"}, {"name": "feature", "value": "登录失败"}, {"name": "parentSuite", "value": "test_dir.Login"}, {"name": "subSuite", "value": "TestLoginFail"}, {"name": "host", "value": "DESKTOP-9JRI8LF"}, {"name": "thread", "value": "17212-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_dir.Login.test_001_loginfail"}]}