{"name": "测试错误账号、正确密码情况下的登录", "status": "passed", "description": "登录失败：测试错误账号、正确密码登录", "start": 1749803171091, "stop": 1749803175983, "uuid": "0bb322c7-429d-402a-88d4-d3cedce5576c", "historyId": "fb5eb2d9aff400899ae5d6cfdecce615", "testCaseId": "fb5eb2d9aff400899ae5d6cfdecce615", "fullName": "test_dir.Login.test_002_loginfail.TestLoginFail#test_login_fail_case", "labels": [{"name": "suite", "value": "登录"}, {"name": "feature", "value": "登录失败"}, {"name": "parentSuite", "value": "test_dir.Login"}, {"name": "subSuite", "value": "TestLoginFail"}, {"name": "host", "value": "DESKTOP-9JRI8LF"}, {"name": "thread", "value": "17212-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_dir.Login.test_002_loginfail"}]}