{"name": "测试错误账号、正确密码情况下的登录", "status": "passed", "description": "登录失败：测试错误账号、正确密码登录", "attachments": [{"name": "stderr", "source": "ea845841-3ebc-4974-89f2-966a4d18a7ea-attachment.txt", "type": "text/plain"}], "start": 1749455227563, "stop": 1749455232435, "uuid": "c9e27e18-7b9c-4baf-b031-1bdeeb51883e", "historyId": "fb5eb2d9aff400899ae5d6cfdecce615", "testCaseId": "fb5eb2d9aff400899ae5d6cfdecce615", "fullName": "test_dir.Login.test_002_loginfail.TestLoginFail#test_login_fail_case", "labels": [{"name": "feature", "value": "登录失败"}, {"name": "suite", "value": "登录"}, {"name": "parentSuite", "value": "test_dir.Login"}, {"name": "subSuite", "value": "TestLoginFail"}, {"name": "host", "value": "DESKTOP-9JRI8LF"}, {"name": "thread", "value": "3728-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_dir.Login.test_002_loginfail"}]}