{"name": "测试错误账号、错误密码情况下的登录", "status": "passed", "description": "登录失败：测试错误账号、错误密码登录", "attachments": [{"name": "stderr", "source": "b513c12d-a56c-4a30-a4ee-fa849a8269fb-attachment.txt", "type": "text/plain"}], "start": 1749455232439, "stop": 1749455237242, "uuid": "35ce06b3-df78-4baf-b6d9-fa54e199af64", "historyId": "a85432e1f09ae03b641ca9cf8de7a5a5", "testCaseId": "a85432e1f09ae03b641ca9cf8de7a5a5", "fullName": "test_dir.Login.test_003_loginfail.TestLoginFail#test_login_fail_case", "labels": [{"name": "feature", "value": "登录失败"}, {"name": "suite", "value": "登录"}, {"name": "parentSuite", "value": "test_dir.Login"}, {"name": "subSuite", "value": "TestLoginFail"}, {"name": "host", "value": "DESKTOP-9JRI8LF"}, {"name": "thread", "value": "3728-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_dir.Login.test_003_loginfail"}]}