{"name": "测试错误账号、正确密码情况下的登录", "status": "passed", "description": "登录失败：测试错误账号、正确密码登录", "attachments": [{"name": "stderr", "source": "61e3ed54-c4c9-4730-9837-3eea9d567674-attachment.txt", "type": "text/plain"}], "start": 1749455098166, "stop": 1749455103099, "uuid": "13aedc85-93e4-41e5-afd8-b614c3a7ec65", "historyId": "fb5eb2d9aff400899ae5d6cfdecce615", "testCaseId": "fb5eb2d9aff400899ae5d6cfdecce615", "fullName": "test_dir.Login.test_002_loginfail.TestLoginFail#test_login_fail_case", "labels": [{"name": "suite", "value": "登录"}, {"name": "feature", "value": "登录失败"}, {"name": "parentSuite", "value": "test_dir.Login"}, {"name": "subSuite", "value": "TestLoginFail"}, {"name": "host", "value": "DESKTOP-9JRI8LF"}, {"name": "thread", "value": "6696-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_dir.Login.test_002_loginfail"}]}