{"name": "测试正确账号、错误密码情况下的登录", "status": "passed", "description": "登录失败：测试正确账号、错误密码登录", "attachments": [{"name": "stdout", "source": "a732b8d0-1c43-4ae7-9b8c-508735089c14-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "c10facd1-2863-4e01-ae18-60a5ac8ac01f-attachment.txt", "type": "text/plain"}], "start": 1749455090799, "stop": 1749455098163, "uuid": "b5f4a36f-f105-4f66-8586-a4a773fb48b6", "historyId": "9bafb470a3f5b2bc06ae6138b0479d4f", "testCaseId": "9bafb470a3f5b2bc06ae6138b0479d4f", "fullName": "test_dir.Login.test_001_loginfail.TestLoginFail#test_login_fail_case", "labels": [{"name": "suite", "value": "登录"}, {"name": "feature", "value": "登录失败"}, {"name": "parentSuite", "value": "test_dir.Login"}, {"name": "subSuite", "value": "TestLoginFail"}, {"name": "host", "value": "DESKTOP-9JRI8LF"}, {"name": "thread", "value": "6696-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_dir.Login.test_001_loginfail"}]}